### ISSUE TITLE
Have a 'factor' sub plugin type

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_mfa#11]
* [x] factors have a priority / order. I'm thinking for simplicity this is declared by the plugin and cannot be changed. Some factors which have no login flow like ip would be ordered at first. 
* [x] factors have a score. This could default to 1, but we able to override this
* [x] you will have a global 'must have X score' in order to login
* [x] each factor should have a method needs_setup()
* [x] have a admin setting which renders a table to manage all the plugins, when each is enabled, the score, the priority.
* [x] have an auto loaded form:

```
class /factor/plugin/classes/forms/login.php - for login flow (eg enter your qr code)
class /factor/plugin/classes/forms/setup.php - for setup flow (eg generate a code)
```

When you turn it on you can say 'you need at least X made up of other factors to login', ie an ip factor is 1, and totp with worth 1, and you need 1 to login.

* [ ] when you login lets say via an ip network, we need to know that you must now also setup other factors. The 'ip' one has not setup. But the totp on does, so you need to be ask to set it up so that you can come back later when not on the corporate ip network.

**Comment by golenkovm** [comment]
Done by merging https://github.com/catalyst/moodle-tool_mfa/pull/53 into master branch
