### ISSUE TITLE
Have an 'email' factor

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_mfa#12]
* [x] has_setup() = false
* [x] is_ready() = do they have an email, and validate_email() + over_bounce_threshold()
* [x] login flow, sends as email with a code, you copy the code into the login form.
* [x] the email also ha the ip address and UA and anything else handy that might help identify the malicious user
* [ ] would usually be very low priority, eg last in the list
* [x] the email should also have a 'This wasn't me' link. The one upside of this approach is that even if your email was compromised you might still see the email. If you do then you can click on the link and it will:
  * [x] work even if you yourself are not logged in (ie you were just doing something else and saw it, it's obviously not you, you need to mitigate it ASAP, and your moodle account may be compromised so you can't actually log in anyway)
  * [x] invalidate the code so the malicious person can't use it 
  * [x] even if they had used that code and logged in, when you click that link it will log them out remotely.
  * [x] log an event with details of the ip address, browser UA and anything else
  * [x] perhaps suspend your account until you can look into it more (needs an option for this)

This still isn't perfect as the person checking your email could also delete the email.

To cleanly do this, a factor can also return a state of 'hard fail' in addition to either a 'yes' (ie yes I'm in the ip range), a no (I'm not in the ip range but thats ok). If any factor returns a fail then the login flow is instantly over.

**Comment by Peterburnett** [comment]
Tasks before revoking functionality

- [ ] Code valid timer, 30 mins etc - user preference

- [ ] Code revoke token - user preference

**Comment by Peterburnett** [comment]
- [ ] Link to pass factor in email.
- [ ] Email template
- [ ] Geolocation
