### ISSUE TITLE
Phpunit.xml isnt picked up by Travis CI

### ISSUE THREAD

**Issue by Peterburnett** [catalyst/moodle-tool_mfa#125]
Currently moot, as it seems that testsuites inside phpunit.xml aren't even run by moodle-plugin-ci. Logged for visibility

**Comment by Peterburnett** [comment]
Travis does pick up the phpunit xml configuration, and the commands seem to be firing properly. The exact same commands from travis run perfectly locally, and fire the privacy checks, but it isnt fired in Travis. Needs more investigation

**Comment by dmitriim** [comment]
Travis is not been used anymore... closing this one off.
