### ISSUE TITLE
On the mfa plugin manage page show a summary of good conditions for login

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_mfa#14]
* [x] when this is loaded or saved show a summary table which lists the conditions based on the scores and priority.
* [ ] ~~have help text which says you probably want the factors with the highest score listed first.~~

eg if you require a score of 100 and you have:

```
auth,saml => 100
iprange => 100
totp => 100
```

The it will show:

```
You must be:
* logged in via saml
OR
* on a secure network
OR
* use TOTP
```

If you then change the 3 scores to 50 then it would say:

```
You must be:
* logged in via saml AND on a secure network
OR
* logged in via saml AND use TOTP
OR
* on a secure network AND use TOTP
```

**Comment by golenkovm** [comment]
Done 
#69
