### ISSUE TITLE
privacy provider missing functions

### ISSUE THREAD

**Issue by danmarsden** [catalyst/moodle-tool_mfa#147]
the tool_mfa table contains user information and the privacy class should implement the following functions to deal with data from this table:

get_contexts_for_userid - to explain where data is held within Moodle for your plugin.
export_user_data - to export a user’s personal data from your plugin.
delete_data_for_all_users_in_context - to delete all data for all users in the specified context.
delete_data_for_user - to delete all user data for the specified user, in the specified contexts.
get_users_in_context - to locate the users who hold any personal data in a specific context.
delete_data_for_users - to delete data for multiple users in the specified context.

**Comment by danmarsden** [comment]
please note - this will likely cause php unit tests to fail on sites that have this plugin installed.

**Comment by brendanheywood** [comment]
I'd prefer to see https://github.com/catalyst/moodle-tool_mfa/issues/125 fixed first that that this is properly picked up by travis instead of later
