### ISSUE TITLE
Grace notification is shown even if there is enough factors to authenticate

### ISSUE THREAD

**Issue by golenkovm** [catalyst/moodle-tool_mfa#150]
How to replicate:

- As the first factor add IP Range with weight = 100 and add your IP to Safe IP ranges.
- As the second factor add Grace period with weight = 100.
- Log out and log in.

Despite the fact that IP Range gives you 100 point Grace notification is shown on the main page after login.

![image](https://user-images.githubusercontent.com/22066290/71959313-90672600-3246-11ea-9612-443167a5efad.png)
![image](https://user-images.githubusercontent.com/22066290/71959377-b7bdf300-3246-11ea-8955-4c717277b386.png)

**Comment by brendanheywood** [comment]
This is exactly how it is supposed to work, so if anything this is a documentation task

**Comment by Peterburnett** [comment]
Information on the behaviour of gracemode and nosetup for optional rollout have been added to the readme.
