### ISSUE TITLE
get_no_redirect_urls should check all factors

### ISSUE THREAD

**Issue by Peterburnett** [catalyst/moodle-tool_mfa#151]
Currently it checks only enabled factors, it should check all factors. Causes redir errors with securityquestions plugin if the securityquestions factor isn't enabled

**Comment by brendanheywood** [comment]
Not 100% sure about this one, I'd keep it as a documentation issue to start with until we find more use cases either for or against

**Comment by Peterburnett** [comment]
I actually changed this in the last merged PR, I forgot to update the issue, happy to change it back. It just means that with security questions, you dont have to have the factor enabled, to avoid a redirect error.

**Comment by brendanheywood** [comment]
nah leave as is, we'll close this
