### ISSUE TITLE
MVP for subplugin based MFA

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_mfa#16]
* [x] first determine resolve all of the no-input factors such as iprange
* [x] now if we still don't have enough points work down the list of factors in turn
* [x] trigger each factors once, this will send an email, or send a test etc. TOTP doesn't need this.
* [x] then render the factors login flow form eg /topt/classes/forms/login
* [x] each factor is responsible for managing its state and mutating and resolving it's state. ie if the user submits the form, and the code is correct then change the state to 'Yes'. If they didn't receive the code and want to skip this factor then it resolves to 'No'
* [x] now control passes back to the main plugin, and it moves to the next plugin down the line.
* [x] if we have enough points then we mark this in the session and the user goes on their way
* [x] if we run out of factors then we send an error message and log them out
* [x] if we time out then we log them out
* [x] if at any time any single factor resolves to fail then we log them out

**Comment by golenkovm** [comment]
Done by merging #53 into master branch
