### ISSUE TITLE
Have a WebAuthn factor ( Yubikey factor / U2F / Fido / CTAP )

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_mfa#20]
https://en.wikipedia.org/wiki/WebAuthn

https://developer.mozilla.org/en-US/docs/Web/API/Web_Authentication_API

Testing demo site:
https://webauthn.io/

Internal WR: https://wrms.catalyst.net.nz/wr.php?request_id=325417

**Comment by brendanheywood** [comment]
Good reading:

https://m.signalvnoise.com/basecamp-now-supports-security-keys-for-two-factor-authentication-thanks-to-webauthn/

**Comment by Dagefoerde** [comment]
here's a rather simple guide on how to implement U2F: https://developers.yubico.com/U2F/Libraries/Using_a_library.html ,
with a U2F server library in PHP at: https://github.com/Yubico/php-u2flib-server (by the Yubikey vendors, but apparently usable with U2F by other vendors too).

Sharing this here because I've been wanting to implement 2FA for Moodle for a long time and had these resources saved for that purpose. Thanks @brendanheywood for creating tool_mfa and for making the necessary changes in core! I love it.

**Comment by brendanheywood** [comment]
you are welcome @Dagefoerde - are you in a position to help with either a pull request or to sponsor the webauth factor?

**Comment by Dagefoerde** [comment]
As I said, I've been wanting to do this as a side project for a while and I might once I find the time. However, right now I can't really make any reliable promises as I am trying to focus on my dissertation.

**Comment by Dagefoerde** [comment]
Working on this in the context of #MootDACH20 now! :)

**Comment by brendanheywood** [comment]
> Working on this in the context of #MootDACH20 now! :)

Cool! :)

**Comment by arjenlentz** [comment]
> Working on this in the context of #MootDACH20 now! :)

Sehr schön, danke @Dagefoerde !

Mfg, Arjen.
(CISO, Catalyst Australia)

**Comment by nadavkav** [comment]
UPDATE: https://android-developers.googleblog.com/2022/10/bringing-passkeys-to-android-and-chrome.html

**Comment by brendanheywood** [comment]
That new spec is very cool - and I think ultimately it should be in core as a first class auth method rather than a second factor. We’d need that to support login to the moodle mobile app working seamlessly with the web login

**Comment by nadavkav** [comment]
@brendanheywood , Is there any Tracker issue about implementing this in core?

**Comment by brendanheywood** [comment]
No but I intend to make one

**Comment by brendanheywood** [comment]
Just made https://tracker.moodle.org/browse/MDL-76125

**Comment by danmarsden** [comment]
We've just merged a webauthn factor into the main branch - thanks to Swissbit for funding the development - we'll do some further testing and look to publish this in the plugins db soon.
