### ISSUE TITLE
 When MFA is activated, images served from pluginfile.php are not displayed

### ISSUE THREAD

**Issue by jnolbertovm** [catalyst/moodle-tool_mfa#225]
When the MFA is activated, the images that are served from pluginfile.php are not displayed and always redirects to the screen where you must enter the code that was sent by email

**Comment by Peterburnett** [comment]
This sounds like it should likely have an exception added, for direct file viewing in the manager, similar to some of the pages that are already excepted. If you are able, we are open to community PRs to fix the issue.

**Comment by brendanheywood** [comment]
@jnolbertovm can you please flesh out the entire steps to reproduce?

**Comment by alphadijkstra** [comment]
I opened a PR to fix this.
https://github.com/catalyst/moodle-tool_mfa/pull/246

In the meantime this can be fixed by adding the following code to the ``manager.php`` file in the classes folder.
```php
// Dont redirect logo images from pluginfile.php (for example: logo in header)
$authurl = new \moodle_url('/pluginfile.php/1/core_admin/logocompact/');
if ($url->compare($authurl)) {
  return self::NO_REDIRECT;
}
```
