### ISSUE TITLE
Moodle app (mobile) bypasses MFA

### ISSUE THREAD

**Issue by alphadijkstra** [catalyst/moodle-tool_mfa#253]
Using the Moodle app bypasses any MFA factor.

**Comment by bozicm** [comment]
Are you sure? We have mobile working alright in our case of just limiting admin access to a certain network. How did you setup the MFA factors?

**Comment by brendanheywood** [comment]
I'll treat this as a documentation task, the MFA can be enforced but you need to setup the auth to be done in browser rather than in app.

tool_mobile | typeoflogin = Via a browser window

I've added this to the readme here:

https://github.com/catalyst/moodle-tool_mfa#moodle-mobile-app
