### ISSUE TITLE
GA app overwrites existing account with the same name

### ISSUE THREAD

**Issue by golenkovm** [catalyst/moodle-tool_mfa#26]
I noticed a GA app bug/feature.
It silently overwrites existing account if you feed it by a new one with the same name.

ie when you generate qrcode using first secret code with a uri like this:
'otpauth://totp/mike:golenkovm@gmail.com?secret=FIRSTSECRETCODE&issuer=Moodle'
GA app creates an account with name "Moodle (mike:golenkovm@gmail.com)". Then we store factor with FIRSTSECRETCODE in db.

When you decide to add one more factor you click Add totp factor we draw a new qr code with new secret code with uri like this:
'otpauth://totp/mike:golenkovm@gmail.com?secret=SECONDSECRETCODE&issuer=Moodle'

If you scan this qr code with a new device - GA app will just create an account "Moodle (mike:golenkovm@gmail.com)" as usual.

However, if you (intentionally or unintentionally) scan it with you first device that already has this account,
GA app will silently overwrites the first one.

So, finally, you will have only one "Moodle (mike:golenkovm@gmail.com)" account on your device. Second one.
And the first one will be permanently lost.

Pobably it's not critical, but we will have active orphaned totp factor in user profile that is never used again.

**Comment by brendanheywood** [comment]
https://github.com/google/google-authenticator/wiki/Key-Uri-Format

The 'label' should be a nice human readable combinations of both the moodle site short name as well as the domain of the moodle without the https://

The user should be the username. (email may also work but isn't guaranteed to be unique unless $CFG->allowaccountssameemail is on)

Issuer should be identical to the label

**Comment by golenkovm** [comment]
Implemented in commits:
https://github.com/catalyst/moodle-tool_mfa/commit/f9ee1ab468f8e6f51bfa7075aa6b15ca43b017ff
https://github.com/catalyst/moodle-tool_mfa/commit/bd90cdbb3e464885b632358241bce0a6b58c970b
https://github.com/catalyst/moodle-tool_mfa/commit/b0be8378406f8712fa7d6cef0d18e7873235c160
