### ISSUE TITLE
Add a totp link on the totp setup page as a third alternative to the qr code and manual setup

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_mfa#271]
Use story:

1) you are on a mobile device and trying to setup totp
2) you can scan the qr code, because you are on the device
3) so you resort to manually adding the totp setup using the secret key and mode etc

But there is no reason why we can't just directly render a link to like this:

otpauth://totp/Some%20moodle%20site?secret=123456&issuer=Moodle

You just tap it and you're done, no typing.

(It is worth warning people that putting the totp onto the same device that they are logging in on does weaken mfa but they are going to do this regardless)

**Comment by Peterburnett** [comment]
Closed in #273
