### ISSUE TITLE
SMS based authentication

### ISSUE THREAD

**Issue by ratishsaini** [catalyst/moodle-tool_mfa#275]
Hi, just want to know if this plugin can implement SMS based 2-factor authentication.

**Comment by ScottVerbeek** [comment]
@Peterburnett Arjen inclined you will be able to answer this question.

**Comment by Peterburnett** [comment]
Hi @ratishsaini 
Currently the plugin supports SMS MFA using the Amazon AWS SNS service. Read here for further details: 

https://aws.amazon.com/sns/?whats-new-cards.sort-by=item.additionalFields.postDateTime&whats-new-cards.sort-order=desc
