### ISSUE TITLE
Unable to setup security questions

### ISSUE THREAD

**Issue by abdullahsuleman** [catalyst/moodle-tool_mfa#297]
Using moodle 3.10. The plugin is installed. I do not see any option to setup the security questions for auth. How am I supposed to do that? The documents were of no help...

**Comment by SamMoher** [comment]
I've come across this as well. I'm on Moodle version 3.9.3+.

**Comment by abdullahsuleman** [comment]
I am able to set the security questions but they do not appear upon logging in. Probably outdated plugin?

**Comment by brendanheywood** [comment]
The security questions 'factor' is not fully implemented, what IS implemented is enough for the two plugins to not clash with each other as they both try to intercept the login flow, so this gives priority to the MFA to plugin to handle mfa first.

The full security questions factor issue is here: https://github.com/catalyst/moodle-tool_mfa/issues/13
