### ISSUE TITLE
Instructions on how to set up SMS

### ISSUE THREAD

**Issue by TimmyzBeach** [catalyst/moodle-tool_mfa#300]
I have the plugin, and the local_aws prerequisite installed on a Moodle server running version 3.10.4+ (Build: 20210604) (2020110904.06). I have SNS (and Pinpoint) configured for production use in AWS, in the us-east-1 region. A new IAM user with permissions to SNS Text Messaging was created, and the key/secret from that user is used in the MFA Plugin SMS configuration. However, I cannot get Moodle to set up a mobile number, as I never receive the text message. I have successfully sent text message via the console, and I have tried using "0" and "1" in the setup, in conjunction with +1, and without for the phone number in Moodle.

What are the steps necessary to get your plugin to send a text message via SNS?

**Comment by hilmiwicak** [comment]
@TimmyzBeach How do you manage to solve this? I'm currently trying to setup the SMS but the configuration in the README doesn't tell anything about setting up.
