### ISSUE TITLE
Issue with Edumy Theme (must include include "<?php echo $OUTPUT->main_content() ?>)

### ISSUE THREAD

**Issue by mohamedmohamedatia** [catalyst/moodle-tool_mfa#304]
Hi,
I would like to thank you for this plugin.
I tried to use the plugin with a commercial theme called Edumy but I got the below error, So I contacted the theme support and they replied as below. I tried Classic theme and another free theme and it works for me 

**Any idea how can I fix this, or is there a new release of the plugin that will solve this issue?**

ERROR:
**Coding error detected, it must be fixed by a programmer: page layout file [dirroot]/theme/edumy/layout/ccn_minimal.php does not contain the main content placeholder, please include "< ? p-h-p echo $ OUTPUT->main_content() ?>" in theme layout file.**

Theme Support Response:
**"Edumy already does include all required functions for the main content area on the page. It appears that the plugin is using an outdated method of printing content into the body area.
Hope this helps to clarify!"**
![MFA - Classic](https://user-images.githubusercontent.com/30835105/125580043-ee56e949-abd8-43f5-8544-c728095e6353.png)
![MFA-Edumy Issue](https://user-images.githubusercontent.com/30835105/125580045-1cfb54b6-eefd-4d9a-ab61-0bef097d0002.png)

**Comment by mohamedmohamedatia** [comment]
It looks like downloading the version from GitHub fixed the issue, as it is recent than the one in Moodle plugins

**Comment by mohamedmohamedatia** [comment]
it looks like updating to the version in Github fixed the issue for the login but in the user preferences admin/tool/mfa/user_preferences.php the issue still exists and gives the error below 

Coding error detected, it must be fixed by a programmer: page layout file [dirroot]/theme/edumy/layout/columns2.php does not contain the main content placeholder, please include "< ?ph p echo $OUTPUT->main_content() ?>" in theme layout file.

**Comment by danmarsden** [comment]
Hi there, their response sounds very suspicious to me and we do not provide support for custom/paid themes - can you please try to reproduce this with the standard core themes Boost or classic - or even one of the popular open source themes like Moove, adapatable or Fordson and we might be more inclined to take a look.

We review a lot of code for our clients and are occaisionally asked to install paid themes like edumy and we often find that as they are closed source, they contain security and perfomance issues that would require more to fix than the clients paid for their themes.

I'm closing this as "won't fix" but please feel free to comment again here if you are able to reproduce this with a core theme, or an open-source theme and we'd be happy to take another look!

thanks!

**Comment by mohamedmohamedatia** [comment]
Hi, 
Thanks for clarifying this for me, I just want to share the below with you maybe it is useful to someone as it fixed the issue for me. after I reviewed the changes between auth.php in the GitHub version and Moodle Plugins version, I did the following  

in both user_preferences.php and action.php
I moved **echo $OUTPUT->header();** above **$OUTPUT = $PAGE->get_renderer('tool_mfa');**

user_preferences.php exists one 
action.php exist twice

**Comment by danmarsden** [comment]
that sounds incorrect to me - I suspect if you have to make these changes to make it work with your theme, you are likely to run into other issues with this theme in other pages on your site - in particular areas like SCORM or secure windows... I would reccomend you look at a different theme.
