### ISSUE TITLE
I cant login my admin account due to I enable email factor for admin and I did not receive a code in my email.

### ISSUE THREAD

**Issue by Razistarmoon** [catalyst/moodle-tool_mfa#325]
Hi guys, I enabled email factor for admin and I try to relogin just to see if it works but when I try to login it prompts to enter verification code for confirmation but I did not receive a code in my email. Now I cant login my admin account. Please help me

**Comment by danmarsden** [comment]
fastest fix would be to delete the tool/mfa code on your server, then login and hit the uninstall link  for tool_mfa on the admin > plugins page to remove the db level settings for tool_mfa, then if you want to try again, add the tool/mfa code back in place and try again to configure it.

Next time - after configuring it, don't logout, open a private window and try to login in the private window to make sure you've got the settings correct.

**Comment by Razistarmoon** [comment]
> fastest fix would be to delete the tool/mfa code on your server, then login and hit the uninstall link for tool_mfa on the admin > plugins page to remove the db level settings for tool_mfa, then if you want to try again, add the tool/mfa code back in place and try again to configure it.
> 
> Next time - after configuring it, don't logout, open a private window and try to login in the private window to make sure you've got the settings correct.

Thank you it works
