### ISSUE TITLE
Step 2: Apply core patches

### ISSUE THREAD

**Issue by Razistarmoon** [catalyst/moodle-tool_mfa#326]
Please help me to proceed in step 2 installation. I dont know to to apply core patches. Im using go daddy as server. 
![STEP 2](https://user-images.githubusercontent.com/98576124/152289899-dad660b9-39d3-44f7-9461-5d87be32e922.PNG)

**Comment by danmarsden** [comment]
Those versions of Moodle are no longer supported, if you upgrade to a supported release you don't need to apply the patches. If you want free help for upgrading your site, or for help to understand how to modify the core code  the best place to ask is in the community forums on moodle.org - good luck!
