### ISSUE TITLE
Unable to authenticate 

### ISSUE THREAD

**Issue by cjfcmit** [catalyst/moodle-tool_mfa#351]
Hi 

Using email to authenticate. 

If a user clicks 'this wasn't me' and stops the log in attempt they are no longer able to log in.

I cannot locate how / where I am able to reset this for the user to allow them log in again.

Help much appreciated thanks

**Comment by Peterburnett** [comment]
Site Administration -> Plugins -> Admin tools -> MFA -> Reset User Factors is the page to allow for resetting of locked factors.
