### ISSUE TITLE
Site-wide blocks appear on TOTP & Email factor page

### ISSUE THREAD

**Issue by johnhpercival** [catalyst/moodle-tool_mfa#352]
I have found that site-wide blocks appear on the TOTP and email factor pages, and because the user is formally authenticated with Moodle, this can leak sensitive information.

I'm not hugely familiar with Moodle core, but having loooked at how the quiz module does it, I think the fix would be to follow the set_pagelayout() call with a call to show_only_fake_blocks()

```
$PAGE->set_pagelayout('secure');
$PAGE->blocks->show_only_fake_blocks();
```

These two places would need changing:
https://github.com/catalyst/moodle-tool_mfa/blob/master/auth.php#L36
https://github.com/catalyst/moodle-tool_mfa/blob/master/factor/email/email.php#L38

Search for the issue:
https://github.com/catalyst/moodle-tool_mfa/search?q=set_pagelayout+secure

**Comment by johnhpercival** [comment]
As a temporary workaround, the following CSS seems to work at hiding the blocks:

```
body#page-admin-tool-mfa-auth aside#block-region-side-post, body#page-admin-tool-mfa-auth div#showsidebaricon {
    display: none!important;
}
```

**Comment by brendanheywood** [comment]
@johnhpercival we haven't come across this bug, can you shed some light on how to reproduce? I assume you'd have to setup some blocks in the system context in a particular way?

**Comment by parkeyparker** [comment]
The easiest way I've found to replicate this issue is to use admin bookmarks (Go to any admin setting page and click "bookmark this page" in the sidebar block (on Boost and Boost-derived themes). Then when that admin user logs in they get the MFA prompt with the admin bookmarks block appearing to the side...

**Comment by johnhpercival** [comment]
@brendanheywood , as @parkeyparker says, a system-wide block such as Admin Bookmarks, Navigation, Administration will appear in the sidebar area when challenged for MFA credentials.

**Comment by brendanheywood** [comment]
Reproduced and the fix is trivial, thanks @parkeyparker and @johnhpercival
