### ISSUE TITLE
Added a proper url parser and conditions and tests for when we should redirect to mfa setup pages

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_mfa#36]
* [x] Make sure you can't subvert this with a url inside a param
* [x] test for when moodle is installed into a subdirectory

**Comment by brendanheywood** [comment]
This has a lot in common with https://github.com/catalyst/moodle-tool_mfa/issues/68 so maybe do them together

**Comment by Peterburnett** [comment]
Closed in #101
