### ISSUE TITLE
tokenpluginfile.php is blocked by the plugin so it is not possible to download files using that script

### ISSUE THREAD

**Issue by moodlemobile** [catalyst/moodle-tool_mfa#366]
The /tokenpluginfile.php file in Moodle is mostly used for downloading/displaying files from Moodle that are linked externally (for example, when a user receives a forum post summary by email including images or attachments). 

It is also used by the Moodle mobile application as a more secure way to download files (to avoid having to pass the WebService auth token via GET to webservice/pluginfile.php)

So what is happening right now is that the tool_mfa is somewhat preventing the use of tokenpluginfile.php (it automatically ends the user session and redirects to the login page). This is making the app unusable on sites with this plugin installed.

Unfortunately, we have not been able to detect why this is happening. We are happy to provide instructions to reproduce this issue if you have a staging site with this plugin installed where you can enable mobile access.

**Comment by danmarsden** [comment]
thanks team - as mentioned privately it's probably this hook:
https://github.com/catalyst/moodle-tool_mfa/blob/master/lib.php

I'm on the fence whether we should add the tokenfile to the default list of exclusions in redir_exclusions which should fix this or hard-code it as an exclusion in the code.

@Peterburnett any thoughts?

**Comment by danmarsden** [comment]
@moodlemobile I just took a closer look at this and I see we tried to fix this here:
https://github.com/catalyst/moodle-tool_mfa/commit/88b052587fb8a88d0accfcd6f229a716bfbe18df

Maybe all we need to do is update the plugins db with the latest version?

**Comment by danmarsden** [comment]
I've just bumped the version and released to teh plugins db which I'm hoping will have fixed this up. - let us know if not though and we can re-open again! - thanks.
