### ISSUE TITLE
TOTP key length should be increased from 80 to at least 128 bit

### ISSUE THREAD

**Issue by agru** [catalyst/moodle-tool_mfa#383]
The TOTP factor returns a string of 16 characters. This corresponds, after Base32 decoding, to an 80-bit secret key. However, according to the requirement for the OTP algorithm in RFC4226 (see Section 4, R6 there), a 128-bit key is a MUST. Most TOTP apps accept the 80-bit key, but the app FreeOTP as an example does not. Here our users get the following message after scanning the QR code: "Token is unsafe! The token you are attempting to add contains weak cryptographic parameters. Use of this token is stronly discouraged! Please alert your token provider". The key length of the TOTP factor should be increased to 128 bits to avoid this nasty warning.

**Comment by agru** [comment]
PR #382 solves this

**Comment by toheine** [comment]
Great! Thank you. I fell over this exact error this morning while setting up 2FA in Moodle with FreeOTP, so I'm super happy about this solution!

**Comment by danmarsden** [comment]
Thanks team - I'm closing this as "won't fix" in the older branches for now - Moodle now includes the mfa plugin in the core release and so feature/improvements need to land in Moodle core "first". We can backport stuff that lands upstream in Moodle core - so if you get this change into Moodle's core release, feel free to re-open this again for further consideration.
