### ISSUE TITLE
Preferences link to setup MFA does not appear

### ISSUE THREAD

**Issue by jolick** [catalyst/moodle-tool_mfa#391]
Hello,

I would like users to be able to setup TOTP if they want. If they do not want, they should be able to login normally.

My problem is:
- For admins: the option "Multi-factor authentication preferences" does not appear in user preferences if there is a way to log in without needing to set up TOTP.
- For non admins: The option never appears. But they are able to access directly "/admin/tool/mfa/user_preferences.php".

How can I make so that that option appears always for all users, so they are able to setup TOTP if they want?

**Comment by Peterburnett** [comment]
Hi @jolick, the intended solution here is to use the nosetup factor to provide the optional points for users that do not have a factor setup.

Please see #330, there is currently an issue with this route, which is being addressed in #382

**Comment by jolick** [comment]
Hello @Peterburnett.

In the case that I only choose totp, the option "Multi-factor authentication preferences" in the user preferences should also appear  for students right?
In my case it only appears in the admins preferences page, never for other types of users.
