### ISSUE TITLE
For totp show for each device when the code was last verified

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_mfa#40]
The last modified date probably has little value in it's own right as most factors don't really have a meaningful 'edit' concept'. So I'd just reuse this field and update the record every time it is validated.

When editing a totp record for the purposes of renaming a device, it probably makes sense to enforce them reconfirming the code for that specific device too, so the last mod field is serving double duty without needing two fields.

**Comment by golenkovm** [comment]
Done by merging https://github.com/catalyst/moodle-tool_mfa/pull/53 into master branch
