### ISSUE TITLE
Multi-factor authentication 2023041600

### ISSUE THREAD

**Issue by slydrone** [catalyst/moodle-tool_mfa#405]
Just installed this on both our sites and now get the following error when clicking on the set up app

Exception - Call to undefined method tool_mfa\local\form\setup_factor_form::xss_whitelist_static_form_elements()

**Comment by danmarsden** [comment]
Thanks for the report - we've got quite a few different changes being actively worked on right now - looks like I missed some of the Totara specific code we were removing from the plugin yesterday, sorry about that! - I've just pushed a fix that should sort that now.

thanks!

**Comment by slydrone** [comment]
Hi Dan thanks. I am new to the Git hub how do I use the fix ?

**Comment by slydrone** [comment]
Great fixed now thanks Dan
