### ISSUE TITLE
Exception - Call to undefined method tool_mfa\local\form\setup_factor_form::xss_whitelist_static_form_elements()

### ISSUE THREAD

**Issue by ajMatus** [catalyst/moodle-tool_mfa#411]
Hello,

One of our users lost his phone, so I reset his Authenticator App MFA which is the only one we use. Upon reset, and when he tried to reset up he received the error "Exception - Call to undefined method tool_mfa\local\form\setup_factor_form::xss_whitelist_static_form_elements()"

I tested on my end with another use, and confirm it happens with all users. This started to happen after I updated the plugin.

I'm running Moodle: [Moodle](http://moodle.org/) [4.2.1 (Build: 20230612)](http://docs.moodle.org/dev/Releases)
and MFA: 2023041600

Any insights on this issue?

**Comment by danmarsden** [comment]
You will have grabbed a version of the code before #405 - just update your version of the code again and it should be sorted.

**Comment by ajMatus** [comment]
Dan forgive me, but what is the link to the latest code? Moodle directs me to -  https://moodle.org/plugins/download.php/29426/tool_mfa_moodle42_2023041600.zip and it still throws that error after downloading and using that code.

Sort of new to github so not sure where all the compilations etc reside.

**Comment by ajMatus** [comment]
Dan,

So I download this - https://github.com/catalyst/moodle-tool_mfa/archive/refs/heads/MOODLE_400_STABLE.zip

Which I believe is the latest package. But now that I log in it's not asking for my Authenticator App Code that was previously set up. Does this mean that all users who had this up already will have to redo it?
