### ISSUE TITLE
Authenticator app enable

### ISSUE THREAD

**Issue by TTorresCIAT** [catalyst/moodle-tool_mfa#426]
Hi
The email autentication is working fine, but I need to enable the Authenticator app, and I can's find the way to to this, i guess is something about the configuration, somebody can explain to me?

I want to enable just ehe Authenticator app

Best regards

**Comment by danmarsden** [comment]
Hi @TTorresCIAT - if you're looking for free help using Moodle or any of the plugins we provide the best place to ask for this is via the community forums on moodle.org.

Unfortunately this plugin is currently limited on documentation, but it's in the process of being included in the Moodle 4.3 core release, so improved documentation should be coming soon!

thanks!
