### ISSUE TITLE
Totara 18 now includes paragonIE used in totp factor.

### ISSUE THREAD

**Issue by danmarsden** [catalyst/moodle-tool_mfa#437]
Totara 18 (TL-37451) added the paragonIE constant_time_encoding stuff which now conflicts with the totp factor - we probably need to create a new TOTARA_18 branch and remove the external lib.

**Comment by aneno-m-e** [comment]
I just pushed a new TOTARA_18_STABLE branch.
- checked out from the TOTARA_12 branch
- added a commit to switch to using the core library for ParagonIE

**Comment by danmarsden** [comment]
Thanks @aneno-m-e I've just renamed that branch to "TOTARA_18" - removing the stable text and dropped a patch into the readme on all branches mentioning the new branch.

Do you know if the patches mentioned in the readme are still needed on the Totara_18 branch? - also might be worth checking the requires version in teh version.php file to see if we can bump it higher to make it clear Totara 18 is required?

thanks!

**Comment by aneno-m-e** [comment]
I've updated the require version as the library does not exist in earlier versions of Tōtara.

The patches are still required . If #373 is merged, it could be used on this branch as well. A watcher has not been added to Tōtara core yet.

**Comment by danmarsden** [comment]
Thanks!
