### ISSUE TITLE
MFA not Working in Moodle 4.3 (Build: 20231009)

### ISSUE THREAD

**Issue by ajMatus** [catalyst/moodle-tool_mfa#442]
Hello,

I upgraded to Moodle 4.3 (Build: 20231009) and I found my site with being unable to login. I moved out the MFA plugin from the tool directory and I'm back online. Of course, MFA no longer works. Will we be seeing updates/compatibility for Moodle 4.3 (Build: 20231009) anytime soon??

Best,

**Comment by danmarsden** [comment]
The mfa plugin is now part of the core 4.3 release. You should not install it separately.

**Comment by ajMatus** [comment]
Thanks Dan,

I was doing the upgrade how I normally proceed, copying over plugin folders and so I guess I had the old version. Unzipped a new 4.3 package, copied over the mfa folder, and seems all good now. Thanks for the info.
