### ISSUE TITLE
Using email MFA behind VPN with private-range IP addresses results in exception

### ISSUE THREAD

**Issue by basilgohar-asmresearch** [catalyst/moodle-tool_mfa#444]
We are using the email factor but we also connect via a VPN so our IP address is in the private IP rangge (e.g., 10.x.x.x).  This causes an exception when used with the MaxMind GeoIP2 Lite because the IP address is not found.  No email is sent, as well.  The error message I get is as follows:

![image](https://github.com/catalyst/moodle-tool_mfa/assets/144369853/507a7998-6fbe-4e9d-b57e-6165a32fdb78)

Exception - The address 10.130.6.1 is not in the database.

[More information about this error](https://docs.moodle.org/402/en/error/moodle/generalexceptionmessage)
Debug info:
Error code: generalexceptionmessage
Stack trace:

    line 260 of /lib/maxmind/GeoIp2/Database/Reader.php: GeoIp2\Exception\AddressNotFoundException thrown
    line 231 of /lib/maxmind/GeoIp2/Database/Reader.php: call to GeoIp2\Database\Reader->getRecord()
    line 94 of /lib/maxmind/GeoIp2/Database/Reader.php: call to GeoIp2\Database\Reader->modelFor()
    line 41 of /iplookup/lib.php: call to GeoIp2\Database\Reader->city()
    line 43 of /admin/tool/mfa/factor/email/renderer.php: call to iplookup_find_location()
    line 66 of /admin/tool/mfa/factor/email/classes/factor.php: call to factor_email_renderer->generate_email()
    line 217 of /admin/tool/mfa/factor/email/classes/factor.php: call to factor_email\factor::email_verification_code()
    line 52 of /admin/tool/mfa/factor/email/classes/factor.php: call to factor_email\factor->generate_and_email_code()
    line 82 of /admin/tool/mfa/classes/local/form/login_form.php: call to factor_email\factor->login_form_definition_after_data()
    line 1024 of /lib/formslib.php: call to tool_mfa\local\form\login_form->definition_after_data()
    line 107 of /admin/tool/mfa/auth.php: call to moodleform->display()

Our version of Moodle is Moodle Workplace 4.2.2.

When we remove the MaxMind DB file, the email factor works due to the fallback to the 3rd-party geoIP web service, but we cannot use that for security reasons as that would leak users' IP addresses to the 3rd party.

**Comment by Peterburnett** [comment]
Hi @basilgohar-asmresearch 

This one has been fixed here https://github.com/catalyst/moodle-tool_mfa/blob/MOODLE_400_STABLE/factor/email/renderer.php#L69 in commit https://github.com/catalyst/moodle-tool_mfa/commit/d7534ef3e321442a91a246a14be1037c6eb7d15b

Please update the plugin and you should be good to go.
