### ISSUE TITLE
Clicking "I didn't receive a code" for e-mail auths lets the user login anyway

### ISSUE THREAD

**Issue by OliverOPI** [catalyst/moodle-tool_mfa#447]
Expected behaviour: Clicking "I didn't' receive a code" should not result in the user being logged in
Observed behaviour: Clicking "I didn't' receive a code" successfully logs the user in without the auth code

Email auth doesn't appear to be working on our installation. When trying to login, the 2FA auth screen is presented. But clicking "I didn't receive a code" results in the user being logged in anyway. In the Moodle logs, we see this:

![don't have a code](https://github.com/catalyst/moodle-tool_mfa/assets/137098267/27e63fda-ac80-441f-b1e4-9f9da9d8959b)

To be clear, we clicked "I didn't receive a code" even when it was in fact e-mailed to us, as we're just testing.

![auth screen](https://github.com/catalyst/moodle-tool_mfa/assets/137098267/26a0bcd4-845b-4795-95eb-9138e98c567b)

Moodle 4.1.5 (IOMAD edition)

**Comment by SOFASICode** [comment]
hi, it not working with me when i clicked  "I didn't receive a code". it display 
![Capture](https://github.com/catalyst/moodle-tool_mfa/assets/89401813/f87f64a5-bd0d-45e5-8dc6-14e88d50ee7a)
i need issue because i can't access as admin

**Comment by Peterburnett** [comment]
Hi @OliverOPI

The logs indicate that you have 2 factors which DO allow for authentication, as the user passed a capability factor and an auth type factor. Email status was neutral, which shows that email did not provide points as indicated in this issue. The "I didn't receive a code" button does not end the authentication flow, just resolves the email factor and moves on to the next factor.

**Comment by Peterburnett** [comment]
Hi @SOFASICode, if you are locked out from the site as an administrator due to MFA, please run `php /path/to/moodle/admin/cli/cfg.php --name=enabled component=tool_mfa --set=0` to disable the plugin via the CLI config tool and regain access to your site.
