### ISSUE TITLE
Users can´t remove factor and also can´t add second security key or second totp

### ISSUE THREAD

**Issue by All0ne** [catalyst/moodle-tool_mfa#461]
Hello together,
first of all, thank you very much for this great plugin! :)

Actually, I have two problems:
1. optional second factors can no longer be removed
![Bildschirmfoto_20240919_134840](https://github.com/user-attachments/assets/8916073d-edd6-4588-bc0e-039eae03f88f)
![Bildschirmfoto_20240919_134747](https://github.com/user-attachments/assets/a7acc15c-54cc-4d9a-8828-20cf167066cc)
![Bildschirmfoto_20240919_134823](https://github.com/user-attachments/assets/92898820-3358-456e-aaf5-aa607a3eab52)

2. it is no longer possible to add second security keys or totp-apps. This was fine in the past.
![Bildschirmfoto_20240919_134840](https://github.com/user-attachments/assets/8916073d-edd6-4588-bc0e-039eae03f88f)

I still have pictures of accounts that still have two... these can remove the old ones but can no longer add new ones.
![Bildschirmfoto_20240919_135359](https://github.com/user-attachments/assets/7636cf0d-7b75-4530-bb5f-e618c36d47d0)
![Bildschirmfoto_20240919_135343](https://github.com/user-attachments/assets/5fa054ef-bb26-41b3-8090-4d08280a3a59)

Can you help me? :)

Moodle 4.4.3+

**Comment by danmarsden** [comment]
This repositoriy is only for moodke 4.3 and older as the mfa tool is now a standard feature in 4.4 core. The best place to ask for help using moodles core features is the moodle.org community forum - thanks!
