### ISSUE TITLE
PHP Notice: Callback after_config in tool_mfa component should be migrated to new hook callback for core\hook\after_config

### ISSUE THREAD

**Issue by jimsihk** [catalyst/moodle-tool_mfa#463]
**Problem**

When running `php -d max_input_vars=10000 /var/www/html/admin/cli/maintenance.php --enable` with Moodle 4.5 debug messages enabled, below message comes out but no impact on Moodle functionality so far. Not sure if require any changes.

```
PHP Notice:  Callback after_config in tool_mfa component should be migrated to new hook callback for core\hook\after_config* line 7213 of /lib/moodlelib.php: call to debugging()
* line 7280 of /lib/moodlelib.php: call to {closure}()
* line 34 of /lib/classes/hook/after_config.php: call to get_plugins_with_function()
* line 1198 of /lib/setup.php: call to core\hook\after_config->process_legacy_callbacks()
* line 34 of /config.php: call to require_once()
* line 28 of /admin/cli/maintenance.php: call to require()
 in /var/www/html/lib/weblib.php on line 2516
```

**Comment by danmarsden** [comment]
it sounds like you might have incorrectly overwritten the core moodle tool_mfa plugin with a copy of the code from this repository.

tool_mfa is now included in the core codebase - please don't download the plugin/code from here or the plugins db. - just use the versino that is already included in core.
