### ISSUE TITLE
Trust This Device not working for multiple web server

### ISSUE THREAD

**Issue by teo-eskilled** [catalyst/moodle-tool_mfa#464]
Our moodle is on a distributed environment with multiple front end server with REDIS sessions and cache enabled. I've tested that Trust This Device only works if the request is forwarded to the same server. Is there any setting that I can do to make it work in a distributed environment?

**Comment by danmarsden** [comment]
@teo-eskilled the right way to ask questions about how to use the tool_mfa plugin or how to configure it in a certain way is on the moodle.org community forums - especially now that this is no longer a plugin but part of Moodle's core release.

If you would like commercial level support with your Moodle site, feel free to reach out to find out more about the Moodle support services we provide via the links in the readme - thanks!
