### ISSUE TITLE
TOTP setup flow form have the ability to setup additional topt and revoke old ones

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_mfa#5]
* [x] Make a new account preferences page:

https://github.com/catalyst/moodle-tool_securityquestions/blob/master/lib.php#L34

* [x] have ability to revoke each factor, which just disabled it so we have an audit trail

* [x] Each setup should have details of the ip it was created from, the time, and a name. It should also show the last time it was used.

**Comment by golenkovm** [comment]
Done by merging https://github.com/catalyst/moodle-tool_mfa/pull/47 into master branch.
Closing this
