### ISSUE TITLE
Honor user timezone when dispay dates

### ISSUE THREAD

**Issue by golenkovm** [catalyst/moodle-tool_mfa#72]
User preference form.
`Created` and `Last verified` columns

Check all diplayed dates everywhere

**Comment by brendanheywood** [comment]
Just userdate

https://docs.moodle.org/dev/Time_API

**Comment by Peterburnett** [comment]
This issue seems to already be handled in all the places where dates are handled and displayed, e.g. renderer.php. Closing for now, unless other points are present
