### ISSUE TITLE
Have settings for whether MFA should be 'optional,suggested, enforced, grace period'

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_mfa#8]
There will be 2 settings in the MFA setup: a grace mode, and a grace duration

These are all what affects what happens when you attempt to login, but do not have any factors setup.

Grade mode:

* [x] optional, it's just on your preferences page but no prompts

MFA is totally optional, if you choose to set it up, and only if you have set it up, will you account then be required to use MFA to login.

This is almost the same as just being off. This needs some thought around how to handle and detect when you've cancelled a totp input request for example.

* [x] suggested, when you login add a notification

When you login, a notification will be added to your session. So when you end up at your wants url you'll get an info box saying 'please add mfa' with a link

* [x] ~~enforced, when you login you redirect to the setup page~~ won't do

If you attempt to go to any other page you MUST be either served a redirect back to the setup page OR you will be served an error page for situations where you'd end up in a redirect loop.

* [x] graceful, same as above but can be dismissed, but only for a certain period eg 2 weeks. Nice workaround so if you must login for say an exam you can get the job done and come back to it

**Comment by Peterburnett** [comment]
Closed in #105
